name: Deploy

on:
  workflow_dispatch: # Trigger manually from Actions tab after adding CLOUDFLARE_API_TOKEN secret

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 24
      - name: Replace wrangler.toml content
        run: |
          ls -la
          sed -i 's/YOUR_D1_DATABASE_ID/"${{ vars.D1_DATABASE_ID }}"/g' wrangler.toml
          cat wrangler.toml
      - run: npm ci
      - name: Init remote D1 database
        continue-on-error: true
        env:
          CLOUDFLARE_API_TOKEN: ${{ vars.CLOUDFLARE_API_TOKEN }}
        run: npm run db:init:remote      
      - name: Put secret API_KEY
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}      
        run: printf "%s" "${{ vars.API_KEY }}" | npx wrangler secret put API_KEY
      - run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
